add_newline = false

[line_break]
disabled = true

[git_status]
disabled = true

[character]
symbol = "❯"
error_symbol = "✗"
use_symbol_for_status = true
style_success = "bold white"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[python]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[php]
disabled = true